#pragma once
#include <stdint.h>
extern uint32_t _binary_aseprite_pigsy_pattern_name_table__layer_0_bin_start __asm("_binary_aseprite_pigsy_pattern_name_table__layer_0_bin_start");
extern uint32_t _binary_aseprite_pigsy_pattern_name_table__layer_0_bin_end __asm("_binary_aseprite_pigsy_pattern_name_table__layer_0_bin_end");
extern uint32_t _binary_aseprite_pigsy_pattern_name_table__layer_0_bin_size __asm("_binary_aseprite_pigsy_pattern_name_table__layer_0_bin_size");
