#pragma once
#include <stdint.h>
extern uint32_t _binary_scu_dsp_advent_2020_day1_input_bin_start __asm("_binary_scu_dsp_advent_2020_day1_input_bin_start");
extern uint32_t _binary_scu_dsp_advent_2020_day1_input_bin_end __asm("_binary_scu_dsp_advent_2020_day1_input_bin_end");
extern uint32_t _binary_scu_dsp_advent_2020_day1_input_bin_size __asm("_binary_scu_dsp_advent_2020_day1_input_bin_size");
